### ISSUE TITLE
uninitialized constant EffectiveBootstrap::EffectiveGem (NameError)

### ISSUE THREAD

**Issue by yo-gen** [code-and-effect/effective_bootstrap#26]
I am trying to move from Rails 5.2.2 to 6.0.0

We use effective_bootstrap as a dependency of effective_datatables. 
Running bundle install automatically updates effective_datatables which also updates effective_bootstrap from our currently used version 0.5.11 version to 0.11.22

But when trying start the rails server, getting the above error.

Downgrading effective_bootstrap explicitly to 0.6.12 works. (Still to confirm how far it works and where it actually broke)
But the version 0.11.12 is definitely broken with effective_datatables version as 4.14.2

Here's the stacktrace
```

        35: from bin/rails:3:in `<main>'
        34: from bin/rails:3:in `load'
        33: from /Users/yogenaggarwal/Desktop/projects/ekanek/cms/bin/spring:15:in `<top (required)>'
        32: from /Users/yogenaggarwal/Desktop/projects/ekanek/cms/bin/spring:15:in `require'
        31: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        30: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        29: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        28: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        27: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        26: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        25: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        24: from /Users/yogenaggarwal/Desktop/projects/ekanek/cms/bin/rails:9:in `<top (required)>'
        23: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        22: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        21: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<main>'
        20: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
        19: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
        18: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        17: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        16: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        15: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `perform'
        14: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `tap'
        13: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:141:in `block in perform'
        12: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        11: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        10: from /Users/yogenaggarwal/Desktop/projects/ekanek/cms/config/application.rb:7:in `<main>'
         9: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bundler-2.3.25/lib/bundler.rb:186:in `require'
         8: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `require'
         7: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bundler-2.3.25/lib/bundler/runtime.rb:44:in `each'
         6: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `block in require'
         5: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bundler-2.3.25/lib/bundler/runtime.rb:55:in `each'
         4: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bundler-2.3.25/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
         3: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         2: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
         1: from /Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/effective_bootstrap-0.11.22/lib/effective_bootstrap.rb:6:in `<main>'
/Users/yogenaggarwal/.rvm/gems/ruby-2.7.2/gems/effective_bootstrap-0.11.22/lib/effective_bootstrap.rb:12:in `<module:EffectiveBootstrap>': uninitialized constant EffectiveBootstrap::EffectiveGem (NameError)

```

**Comment by matt-riemer** [comment]
Hey I think this has been resolved! Thank you
